name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - "~1.14"
          - "~1.15"
          - "~1.16"
          - "~1.17"
          - "~1.18"
          - "~1.19"
          - "~1.20"
          - "~1.21"
          - "~1.22"

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go_version }}"

      - run: go test ./...
